# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QScrollBar, QScrollArea


class Ui_TFG(object):

    def setupUi(self, TFG):
        TFG.setObjectName("TFG")
        TFG.setFixedSize(587, 340)
        TFG.setStyleSheet("/*Cambiamos el color de la ventana*/\n"
                          "    QMainWindow{\n"
                          "        background-color: #FFFFFF;\n"
                          "    }\n"
                          "\n"
                          "    /*Estilos para el botón*/\n"
                          "    QPushButton{\n"
                          "        font-size: 11px;\n"
                          "    }\n"
                          "    \n"
                          "    /*Definimos el estilo para un efecto hover sobre el botón,\n"
                          "    este cambiará su background cuando pasemos el mouse por\n"
                          "    encima*/\n"
                          "    QPushButton:hover{\n"
                          "    background-color: #018786;\n"
                          "    }\n"
                          "\n"
                          "    /*Definimos los estilos para los QLineEdit*/\n"
                          "    QLineEdit{\n"
                          "        border-radius: 3px;\n"
                          "        border: 2px solid #00796b;\n"
                          "    }\n"
                          "\n"
                          "\n"
                          "    \n"
                          "    /*Definimos el estilo para un efecto hover sobre el botón,\n"
                          "    este cambiará su background cuando pasemos el mouse por\n"
                          "    encima*/\n"
                          "    \n"
                          "\n"
                          "    /*Definimos los estilos para los QLabel*/\n"
                          "    QLabel{\n"
                          "        font-family: \'Roboto\';\n"
                          "    }\n"
                          "\n"
                          "    /*Definimos los estilos para los QLabels cuyos nombres son\n"
                          "    \'label_usuario\' y \'label-password\'*/\n"
                          "    #label_usuario, #label_password{\n"
                          "        font-size: 17px;\n"
                          "        color: #212121;\n"
                          "    }\n"
                          "    \n"
                          "    /*Estilo para el QLable cuyo nombre es #label_login*/\n"
                          "    #label_titulo{\n"
                          "        font-size:15px;\n"
                          "        color: #000000;\n"
                          "    }\n"
                          "")
        self.centralwidget = QtWidgets.QWidget(TFG)
        self.centralwidget.setObjectName("centralwidget")
        self.baceptar = QtWidgets.QPushButton(self.centralwidget)
        self.baceptar.setGeometry(QtCore.QRect(340, 120, 96, 31))
        self.baceptar.setObjectName("baceptar")
        self.barchivo = QtWidgets.QPushButton(self.centralwidget)
        self.barchivo.setGeometry(QtCore.QRect(140, 120, 96, 31))
        self.barchivo.setObjectName("barchivo")
        self.burl = QtWidgets.QPushButton(self.centralwidget)
        self.burl.setGeometry(QtCore.QRect(240, 120, 96, 31))
        self.burl.setObjectName("burl")
        self.label_dir = QtWidgets.QLabel(self.centralwidget)
        self.label_dir.setGeometry(QtCore.QRect(240, 220, 191, 13))
        self.label_dir.setText("")
        self.label_dir.setObjectName("label_dir")
        self.bentrenar = QtWidgets.QPushButton(self.centralwidget)
        self.bentrenar.setGeometry(QtCore.QRect(440, 120, 91, 31))
        self.bentrenar.setObjectName("bentrenar")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(140, 160, 295, 49))
        self.listWidget.setObjectName("listWidget")
        TFG.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TFG)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 21))
        self.menubar.setObjectName("menubar")
        TFG.setMenuBar(self.menubar)

        self.retranslateUi(TFG)
        QtCore.QMetaObject.connectSlotsByName(TFG)

    def retranslateUi(self, TFG):
        _translate = QtCore.QCoreApplication.translate
        TFG.setWindowTitle(_translate("TFG", "MainWindow"))
        self.baceptar.setText(_translate("TFG", "Comenzar"))
        self.barchivo.setText(_translate("TFG", "Archivo"))
        self.burl.setText(_translate("TFG", "URL"))
        self.bentrenar.setText(_translate("TFG", "Entrenar"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    TFG = QtWidgets.QMainWindow()
    ui = Ui_TFG()
    ui.setupUi(TFG)
    TFG.show()
    sys.exit(app.exec_())
